### PR TITLE
Bind `extra_fds` argument to `curl_multi_wait` and `curl_multi_poll`

### PR DESCRIPTION
**Pull request by nojb**
Propose to bind the `extra_fds` argument of [`curl_multi_wait`](https://curl.se/libcurl/c/curl_multi_wait.html) and [`curl_multi_poll`](https://curl.se/libcurl/c/curl_multi_poll.html).

Suggestions to improve the API are welcome!

### CODE REVIEW

**Comment by nojb** [comment]
Friendly ping.

**Review by ygrek — APPROVED** [review]
sorry for the delay, minor comments

**Comment by ygrek** [comment]
cherry-picked in https://github.com/ygrek/ocurl/commit/f76878e8d8a3a83a46feec3ba7a50583592748e6
thanks!

**Comment by nojb** [comment]
Thank you!

**Pull request closed without merging**
